= Task_2: Device datastore CRUD APIs (REST API + DB + vertx framework)
 

Create a simple REST API backend using vert.x framework for IoT devices datastore
which will store all the details related to IoT devices. The application should provide an API
interface to add, update, delete, and get device details.

Sample device details JSON:


{
  "deviceId":"123-asdasd-123",
  "Domain":"smart-transport",
  "state":"MH",
  "city":"Pune",
  "location":{
      "Type":"point",
      "Coordinates":[34.56,76.34]
    },
  "deviceType":"smart-camera"
}.

 

== ToDo’s:
* APIs must provide an interface for CRUD operations.
* Use a database for storing details (MongoDB).
* Try to demonstrate the use of Future & Promise.
* Complete Junit test cases.
* Create a Postman collection to test APIs.



image:https://img.shields.io/badge/vert.x-4.4.5-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean compile exec:java
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://discord.gg/6ry7aqPWXy[Vert.x Discord]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


